---
abstract: 'Simple Moose/Mouse-based framework for Subversion hooks'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  App::Cmd::Tester: 0
  Carp: 0
  Const::Fast: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
  Test::Most: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SVN-Simple-Hook
recommends:
  Alien::SVN: 0
requires:
  Any::Moose: 0
  English: 0
  Modern::Perl: 0
  MouseX::App::Cmd: 0
  MouseX::Types::Common: 0
  MouseX::Types::Mouse: 0
  MouseX::Types::Path::Class: 0
  Path::Class: 0
  SVN::Client: 0
  SVN::Core: 0
  namespace::autoclean: 0
  perl: 5.010
  utf8: 0
resources:
  bugtracker: https://github.com/mjgardner/svn-simple-hook/issues
  homepage: http://metacpan.org/release/SVN-Simple-Hook
  repository: git://github.com/mjgardner/svn-simple-hook.git
version: 0.301
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/MakeMaker'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::Prepender
      name: Prepender
      version: 1.103470
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: recommends
      name: Recommends
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::UnusedVarsTests
      name: '@TestingMania/UnusedVarsTests'
      version: 1.100860
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@TestingMania/PortabilityTests'
      version: 1.111840
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@TestingMania/Test::Version'
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@TestingMania/PodCoverageTests'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@TestingMania/CompileTests'
      version: 1.110930
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@TestingMania/Test::CPAN::Changes'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@TestingMania/MetaTests'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@TestingMania/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@TestingMania/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: '@TestingMania/CriticTests'
      version: 1.111450
    -
      class: Dist::Zilla::Plugin::DistManifestTests
      name: '@TestingMania/DistManifestTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@TestingMania/Test::CPAN::Meta::JSON'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::SynopsisTests
      name: '@TestingMania/SynopsisTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@TestingMania/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: '@TestingMania/Test::Pod::LinkCheck'
      version: 1.001
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@TestingMania/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::MojibakeTests
      name: '@TestingMania/MojibakeTests'
      version: 0.3
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@TestingMania/PodSyntaxTests'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::PerlTidy
      name: PerlTidy
      version: 0.11
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: ReadmeAnyFromPod
      version: 0.103522
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: ReadmePodInRoot
      version: 0.103522
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: ReportVersions
      version: 1.110730
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: InstallGuide
      version: 1.101461
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Git/Check'
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Git/Commit'
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Git/Tag'
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Git/Push'
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: Git::CommitBuild
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@GitHub/GitHub::Meta'
      version: 0.10
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@GitHub/GitHub::Update'
      version: 0.10
    -
      class: Dist::Zilla::Plugin::LocalBrew
      name: LocalBrew
      version: 0.02
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: InstallRelease
      version: 0.007
    -
      class: Dist::Zilla::Plugin::Twitter
      name: Twitter
      version: 0.010
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.200012
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200012
