---
abstract: 'Simple Moose-based framework for Subversion hooks'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  App::Cmd::Tester: 0
  Carp: 0
  File::Find: 0
  File::Temp: 0
  MooseX::App::Cmd: 0
  MooseX::App::Cmd::Command: 0
  Readonly: 0
  Scalar::Util: 0
  Test::More: 0.94
  Test::Most: 0
  perl: 5.004
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SVN-Simple-Hook
recommends:
  Alien::SVN: 0
requires:
  English: 0
  Modern::Perl: 0
  Moose: 0
  Moose::Role: 0
  MooseX::App::Cmd: 0
  MooseX::Getopt: 0
  MooseX::Has::Sugar: 0
  MooseX::Types::Common: 0
  MooseX::Types::Common::Numeric: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  SVN::Client: 0
  namespace::autoclean: 0
  perl: 5.010
  utf8: 0
resources:
  bugtracker: https://github.com/mjgardner/svn-simple-hook/issues
  homepage: http://search.cpan.org/dist/SVN-Simple-Hook/
  repository: git://github.com/mjgardner/svn-simple-hook.git
version: 0.214
